DROP TABLE IF EXISTS dishes CASCADE;
CREATE TABLE dishes (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(4,2) NOT NULL,
  image_url VARCHAR(255),
  category VARCHAR(255)
);
